export const PROGRAMMING_LANGUAGES = [
  { name: 'Java', experience: null },
  { name: 'Python', experience: null },
  { name: 'JavaScript', experience: null },
  { name: 'TypeScript', experience: null },
  { name: 'C#', experience: null },
  { name: 'C', experience: null },
  { name: 'C++', experience: null },
  { name: 'Swift', experience: null },
  { name: 'Ruby', experience: null },
  { name: 'Scala', experience: null },
  { name: 'Go / Golang', experience: null },
  { name: 'HTML', experience: null },
  { name: 'CSS', experience: null },
];

export const LIBRARIES_FRAMEWORKS = [
  { name: 'Spring Boot', experience: null },
  { name: 'React', experience: null },
  { name: 'Redux', experience: null },
  { name: 'Angular', experience: null },
  { name: 'Node.js', experience: null },
  { name: 'Express.js', experience: null },
  { name: '.NET', experience: null },
  { name: 'Django', experience: null },
  { name: 'Flask', experience: null },
  { name: 'FastAPI', experience: null },
  { name: 'React Native', experience: null },
  { name: 'Flutter', experience: null },
  { name: 'Ruby on Rails', experience: null },
];

export const TOOLS = [
  { name: 'Microservices', experience: null },
  { name: 'SQL', experience: null },
  { name: 'MongoDB', experience: null },
  { name: 'MySQL', experience: null },
  { name: 'SQL Server', experience: null },
  { name: 'PostgreSQL', experience: null },
  { name: 'AWS', experience: null },
  { name: 'Azure', experience: null },
  { name: 'Google Cloud / GCP', experience: null },
  { name: 'Android Development', experience: null },
  { name: 'iOS development', experience: null },
  { name: 'Tableau', experience: null },
  { name: 'Excel', experience: null },
  { name: 'Power BI', experience: null },
];
