export const PREFERRED_JOB_ROLES = [
  { value: 'Engineering Leadership', label: 'Engineering Leadership' },
  {
    value: 'Software Development Engineer (Backend)',
    label: 'Software Development Engineer (Backend)',
  },
  {
    value: 'Software Development Engineer (Frontend)',
    label: 'Software Development Engineer (Frontend)',
  },
  {
    value: 'Software Development Engineer (Full Stack)',
    label: 'Software Development Engineer (Full Stack)',
  },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Android Engineer', label: 'Android Engineer' },
  { value: 'iOS Engineer', label: 'iOS Engineer' },
  { value: 'Devops Engineer', label: 'Devops Engineer' },
  { value: 'Support Engineer', label: 'Support Engineer' },
  { value: 'Research Engineer', label: 'Research Engineer' },
  { value: 'Engineering Intern', label: 'Engineering Intern' },
  { value: 'QA Engineer', label: 'QA Engineer' },
  { value: 'Co-founder', label: 'Co-founder' },
  { value: 'SDET', label: 'SDET' },
  { value: 'Product Manager', label: 'Product Manager' },
  { value: 'Product Designer', label: 'Product Designer' },
  { value: 'Backend Architect', label: 'Backend Architect' },
  { value: 'Program Manager', label: 'Program Manager' },
  { value: 'Release Engineer', label: 'Release Engineer' },
  { value: 'Security Leadership', label: 'Security Leadership' },
  { value: 'Database Administrator', label: 'Database Administrator' },
  { value: 'Data Analyst', label: 'Data Analyst' },
  { value: 'Data Engineer', label: 'Data Engineer' },
];
