export const PREFERRED_JOB_LOCATIONS = [
  { value: 'Bangalore', label: 'Bangalore' },
  { value: 'Pune', label: 'Pune' },
  { value: 'Gurgaon', label: 'Gurgaon' },
  { value: 'Nodia', label: 'Nodia' },
  { value: 'Chennai', label: 'Chennai' },
  { value: 'Delhi', label: 'Delhi' },
  { value: 'Chandigarh', label: 'Chandigarh' },
  { value: 'Kolkata', label: 'Kolkata' },
  { value: 'Mumbai', label: 'Mumbai' },
  { value: 'Jaipur', label: 'Jaipur' },
  { value: 'Varodara', label: 'Varodara' },
  { value: 'Nagpur', label: 'Nagpur' },
  { value: 'Ahmedabad', label: 'Ahmedabad' },
  { value: 'Kochi', label: 'Kochi' },
  { value: 'Mysore', label: 'Mysore' },
  { value: 'Coimbatore', label: 'Coimbatore' },
  { value: 'Bangkok', label: 'Bangkok' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Udaipur', label: 'Udaipur' },
  { value: 'Cochin', label: 'Cochin' },
  { value: 'Remote', label: 'Remote' },
  { value: 'Hubballi', label: 'Hubballi' },
  { value: 'Goa', label: 'Goa' },
  { value: 'Trivandrum', label: 'Trivandrum' },
  { value: 'Indore', label: 'Indore' },
  { value: 'London', label: 'London' },
  { value: 'Bhubaneswar', label: 'Bhubaneswar' },
  { value: 'Melno Park', label: 'Melno Park' },
  { value: 'Dehradun', label: 'Dehradun' },
  { value: 'Hosur', label: 'Hosur' },
  { value: 'Delaware', label: 'Delaware' },
  { value: 'Amsterdam', label: 'Amsterdam' },
  { value: 'California', label: 'California' },
  { value: 'Mohali', label: 'Mohali' },
  { value: 'New Jersey', label: 'New Jersey' },
  { value: 'Arizona', label: 'Arizona' },
  { value: 'North Carolina', label: 'North Carolina' },
  { value: 'Agra', label: 'Agra' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Pondicherry', label: 'Pondicherry' },
];

export const PREFERRED_JOB_ROLES = [
  { value: 'Engineering Leadership', label: 'Engineering Leadership' },
  {
    value: 'Software Development Engineer (Backend)',
    label: 'Software Development Engineer (Backend)',
  },
  {
    value: 'Software Development Engineer (Frontend)',
    label: 'Software Development Engineer (Frontend)',
  },
  {
    value: 'Software Development Engineer (Full Stack)',
    label: 'Software Development Engineer (Full Stack)',
  },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Android Engineer', label: 'Android Engineer' },
  { value: 'iOS Engineer', label: 'iOS Engineer' },
  { value: 'Devops Engineer', label: 'Devops Engineer' },
  { value: 'Support Engineer', label: 'Support Engineer' },
  { value: 'Research Engineer', label: 'Research Engineer' },
  { value: 'Engineering Intern', label: 'Engineering Intern' },
  { value: 'QA Engineer', label: 'QA Engineer' },
  { value: 'Co-founder', label: 'Co-founder' },
  { value: 'SDET', label: 'SDET' },
  { value: 'Product Manager', label: 'Product Manager' },
  { value: 'Product Designer', label: 'Product Designer' },
  { value: 'Backend Architect', label: 'Backend Architect' },
  { value: 'Program Manager', label: 'Program Manager' },
  { value: 'Release Engineer', label: 'Release Engineer' },
  { value: 'Security Leadership', label: 'Security Leadership' },
  { value: 'Database Administrator', label: 'Database Administrator' },
  { value: 'Data Analyst', label: 'Data Analyst' },
  { value: 'Data Engineer', label: 'Data Engineer' },
];
